DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS items CASCADE;

create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists requests(
    id bigint generated by default as identity not null constraint requests_pk primary key,
    description  varchar(512) not null,
    requestor_id bigint  not null
);

create table if not exists items(
    id bigint generated by default as identity not null constraint items_pk primary key,
    name varchar(255) not null,
    description varchar(512) not null,
    is_available boolean not null,
    owner_id bigint not null constraint items_users_id_fk references users
        on update cascade on delete cascade,
    request_id bigint constraint items_requests_id_fk references requests
        on update cascade on delete cascade
);



